# Reads the input from one or more CSV word lists generated by merge_lists.py and returns the set of IPA symbols across these files.
# Could be refined to get rid of noise (stress/diphthong/etc. markers).

import sys

symbols = set()

def read_file(file):
	with open(file, 'r', encoding='utf-8') as f:
		for line in f:
			line = line.replace(',', '').strip()
			for symbolIdx in range(len(line)):
				if line[symbolIdx] == 'ʲ':
					symbols.add(line[symbolIdx - 1:symbolIdx + 1])
				elif line[symbolIdx] == '͡':
					symbols.add(line[symbolIdx - 1:symbolIdx + 2])
				else:
					symbols.add(line[symbolIdx])

if __name__ == "__main__":
	n_args = len(sys.argv)

	if n_args < 2:
		sys.stderr.write("Usage: %s INPUT\n" % sys.argv[0])
		sys.exit(1)

	for i in range(1, n_args):
		read_file(sys.argv[i])

	print(symbols)